name: CD DEV
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
on:
  workflow_run:
    workflows: ["CI"]
    branches:
      - dev
    types:
      - completed
jobs:
  docker-master:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: "Recodive/Workflows/.github/workflows/CD Docker.yml@main"
    with:
      context: master/.
      tags: premid/api-master
    secrets:
      GH_NPM_TOKEN: ${{ secrets.GH_NPM_TOKEN }}
    permissions:
      contents: read
      packages: write
  docker-worker:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: "Recodive/Workflows/.github/workflows/CD Docker.yml@main"
    with:
      context: worker/.
      tags: premid/api-worker
    secrets:
      GH_NPM_TOKEN: ${{ secrets.GH_NPM_TOKEN }}
    permissions:
      contents: read
      packages: write
