name: CI Dependencies
on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
jobs:
  automerge:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: fastify/github-action-merge-dependabot@v3.3.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          target: minor
